#!/bin/bash

pkill swaybg
pkill swww-daemon
pkill persway
swww-daemon --format xrgb &
swww img $HOME/dotfiles/bg.gif
persway daemon -e '[tiling] opacity 1' -f '[tiling] opacity 0.85; opacity 1' -l 'mark --add _prev' -d spiral &
